<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    @page { margin: 24px; }
    body { font-family: DejaVu Sans, sans-serif; font-size: 9px; color: #333; }
    h1 { font-size: 18px; color: #2563eb; margin-bottom: 2px; }
    h2 { font-size: 12px; color: #555; margin-top: 18px; margin-bottom: 6px; border-bottom: 1px solid #ddd; padding-bottom: 3px; }
    .sub { color: #888; font-size: 8px; margin-bottom: 12px; }
    .meta { width: 100%; margin-bottom: 10px; }
    .meta td { padding: 3px 8px; font-size: 8px; }
    .meta td:first-child { color: #888; width: 100px; }
    .meta td:last-child { color: #333; font-weight: bold; }
    .config-block { background: #f4f4f4; border: 1px solid #ddd; border-radius: 4px; padding: 8px; font-family: "DejaVu Sans Mono", monospace; font-size: 6.5px; line-height: 1.4; white-space: pre-wrap; word-break: break-all; }
    .footer { margin-top: 20px; text-align: center; font-size: 7px; color: #aaa; border-top: 1px solid #e5e7eb; padding-top: 8px; }
</style>
</head>
<body>
    <h1>{{ $data['hostname'] }}</h1>
    <div class="sub">Device Configuration — Version {{ $data['version'] }}</div>

    <table class="meta">
        <tr><td>Vendor</td><td>{{ $data['vendor'] ?? '—' }}</td></tr>
        <tr><td>Model</td><td>{{ $data['model'] ?? '—' }}</td></tr>
        <tr><td>OS Version</td><td>{{ $data['os_version'] ?? '—' }}</td></tr>
        <tr><td>Serial Number</td><td>{{ $data['serial_number'] ?? '—' }}</td></tr>
        @if ($data['target'])
        <tr><td>Monitored Target</td><td>{{ $data['target']['name'] }} ({{ $data['target']['ip_address'] }})</td></tr>
        @endif
        <tr><td>Saved by</td><td>{{ $data['created_by'] }}</td></tr>
        <tr><td>Saved at</td><td>{{ $data['created_at'] ? \Carbon\Carbon::parse($data['created_at'])->format('Y-m-d H:i') : '—' }}</td></tr>
    </table>

    @if ($data['config_text'])
    <h2>Configuration</h2>
    <div class="config-block">{{ $data['config_text'] }}</div>
    @endif

    <div class="footer">Generated by ArgusNet — {{ now()->format('Y-m-d H:i') }}</div>
</body>
</html>
